using System;

namespace PoliticalTimeline
{
    public enum PolicyId { None, RailNetwork, SchoolMeals, DrugPriceCap, FloodDefenses, GiftBan, CleanAir, DataPrivacy, LegalAid, SafeWater, Libraries, PublicHousing, CleanResearch, WealthTax, HospitalFunding, EnergyPriceCap, PensionIncrease, SchoolRepairs, TradeAgreement, SurveillancePowers, BridgeRepairs, EmergencyGrid, PaidLeave, Childcare, PressFreedom, SoilProtection, ElectionAccess, RuralBroadband, Apprenticeships, PublicTransit, RentProtection, FoodInspection, DisasterInsurance, CyberSecurity, SmallBusinessCredit, VeteransCare, WaterConservation, PublicRecords, WageTheft, RuralClinics, MentalHealth, DepositInsurance, RightToRepair, AntitrustEnforcement, SchoolCooling, PostalAccess, DisasterReserves, CampaignDisclosure, WorkerSafety, PublicBroadcasting, NationalParks, ConsumerRefunds, WhistleblowerProtection }
    public sealed class EnactedPolicy
    {
        public PolicyId Id { get; }
        public DateTime Enacted { get; }
        public EnactedPolicy(PolicyId id,DateTime date) { Id=id; Enacted=date; }
    }
    public static class PolicyLedger
    {
        public static string Title(PolicyId id)
        {
            string[] names={"", "National rail network", "Universal school meals", "Prescription price cap", "Flood defenses", "Federal gift ban", "Clean-air standards", "Personal data protection", "Expanded legal aid", "Safe water program", "Evening libraries", "Public housing", "Clean technology research", "Wealth tax", "Rural hospital funding", "Household energy cap", "Pension increase", "School repair program", "Import trade agreement", "Expanded surveillance", "Bridge repair program", "Emergency grid reserve", "Paid family leave", "Public childcare", "Press protection law", "Soil restoration fund", "Accessible polling places", "Rural broadband", "Paid apprenticeships", "Public transit fund", "Renter protections", "Food safety inspections", "Disaster insurance", "Public cyber defenses", "Small business credit", "Veterans care", "Water conservation", "Open public records", "Wage theft enforcement", "Rural clinic network", "Mental health access", "Deposit insurance", "Right to repair", "Competition enforcement", "School cooling fund", "Rural postal access", "Emergency supply reserves", "Campaign donor disclosure", "Workplace safety standards", "Public broadcasting fund", "National park maintenance", "Consumer refund rights", "Whistleblower protections"};
            return names[(int)id];
        }
        public static string Description(PolicyId id)
        {
            string[] descriptions={"", "Federal funding for a national rail network.", "Federal funding for school lunches.", "Limits on prescription drug prices.", "Investment in levees and drainage.", "Officials may no longer accept gifts.", "Factories must meet emissions limits.", "Rules protect personal information.", "More public funding for legal assistance.", "A program to replace unsafe water pipes.", "Funding for longer library opening hours.", "Public investment in new homes.", "Public funding for clean technology.", "Taxes on wealth fund household relief.", "Federal support for rural hospitals.", "Limits on household energy prices.", "Higher payments for retirees.", "Public funding to repair classrooms.", "Lower barriers to imported goods.", "Broader powers for intelligence agencies.", "Federal funding to repair aging bridges.", "Backup power for essential services.", "Paid time off to care for family.", "Public funding for childcare places.", "Legal safeguards for public-interest reporting.", "Support for restoring damaged farmland.", "Funding for accessible polling locations.", "Investment in rural internet connections.", "Paid training places for new workers.", "Funding for affordable bus and rail services.", "Standards against abusive rental practices.", "More inspectors for food production.", "Public insurance support after disasters.", "Cybersecurity funding for public services.", "Affordable credit for small businesses.", "Expanded care for military veterans.", "Support for efficient water use.", "Clear deadlines for access to public records.", "Enforcement against stolen wages.", "Funding for clinics in underserved rural areas.", "Expanded access to mental health treatment.", "Insures eligible bank deposits against bank failure.", "Owners and independent shops can access repair parts and manuals.", "Resources to investigate anti-competitive mergers and practices.", "Cooling and ventilation improvements for overheated schools.", "Funding to retain postal access in remote communities.", "Rotating reserves of emergency equipment and essential supplies.", "Public reporting of large campaign donations.", "Inspection and enforcement of workplace safety requirements.", "Funding for independent public-interest broadcasting.", "Repairs to trails, visitor facilities and park infrastructure.", "Clear refund rights for defective goods and cancelled services.", "Protection for workers reporting serious wrongdoing."};
            return descriptions[(int)id];
        }
    }
}
